"""
Builder Agent — generates complete, runnable challenge repos from a challenge description.

Split into two phases:
1. Planner — lightweight call to decide clustering, ecosystem, and file manifest
2. Per-repo generator — generates creative files for one repo at a time

Config/boilerplate files (package.json, tsconfig, etc.) are injected from
tools.boilerplate, not generated by the LLM.
"""

import json
from dataclasses import dataclass, field
from pathlib import Path

import config
from tools.file_tools import read_file, write_repo_files, format_files_for_prompt
from tools.llm_client import call_llm, parse_json_from_response
from tools.repo_tools import git_init
from tools.boilerplate import get_boilerplate


# ── Dataclasses ───────────────────────────────────────────────────────────────

@dataclass
class ChallengeRepo:
    name: str
    description: str
    challenges: list[str]
    install_command: str
    test_command: str
    files: dict[str, str]  # relative_path -> content
    ecosystem: str = ""    # "react" | "typescript" | "python" | etc.


@dataclass
class BuildResult:
    repos: list[ChallengeRepo]


@dataclass
class RepoSpec:
    """Blueprint for a single repo, produced by the planner."""
    name: str
    description: str
    challenges: list[str]
    ecosystem: str
    install_command: str
    test_command: str
    creative_files: list[str]  # paths the LLM should generate
    is_ui: bool


@dataclass
class BuildPlan:
    """Output of the planner step."""
    repos: list[RepoSpec]
    clustering_rationale: str
    challenge_type_notes: str


# ── Reference doc filtering ──────────────────────────────────────────────────

# Mapping: ecosystem -> keywords to match against section headers in
# generation-patterns.md.  Matching is word-boundary-aware to prevent
# "Java" from matching "JavaScript".
_PATTERN_KEYWORDS: dict[str, list[str]] = {
    "typescript": ["TypeScript", "JavaScript", "JS Test"],
    "react":      ["TypeScript", "JavaScript", "React", "JS Test"],
    "vue":        [],
    "angular":    ["Angular"],
    "python":     ["Python"],
    "java":       ["Java"],
    "cpp":        ["C++"],
    "cobol":      ["COBOL"],
}

# Keywords for project-templates.md section matching
_TEMPLATE_KEYWORDS: dict[str, list[str]] = {
    "typescript": ["JavaScript / TypeScript"],
    "react":      ["React"],
    "vue":        ["Vue"],
    "angular":    ["Angular"],
    "python":     ["Python"],
    "java":       ["Java"],
    "cpp":        ["C++"],
    "cobol":      ["COBOL"],
}

# Always included regardless of ecosystem
_ALWAYS_INCLUDE = ["Universal", "Decision"]
_ALWAYS_INCLUDE_TEMPLATES = [".gitignore"]


def _split_sections(text: str) -> list[tuple[str, str]]:
    """Split markdown text by ## headings. Returns [(header, content), ...]."""
    sections: list[tuple[str, str]] = []
    current_header = ""
    current_lines: list[str] = []

    for line in text.splitlines(keepends=True):
        if line.startswith("## "):
            if current_header or current_lines:
                sections.append((current_header, "".join(current_lines)))
            current_header = line.strip().lstrip("#").strip()
            current_lines = [line]
        else:
            current_lines.append(line)

    if current_header or current_lines:
        sections.append((current_header, "".join(current_lines)))

    return sections


def _keyword_matches_header(keyword: str, header: str) -> bool:
    """Check if keyword matches in header with word-boundary awareness.

    Prevents 'Java' from matching 'JavaScript' by checking that the
    character after the match (if any) is not alphabetic.
    """
    h = header.lower()
    k = keyword.lower()
    idx = h.find(k)
    if idx == -1:
        return False
    end = idx + len(k)
    if end < len(h) and h[end].isalpha():
        return False
    return True


def _filter_sections(
    sections: list[tuple[str, str]],
    keywords: list[str],
    always_include: list[str],
) -> str:
    """Return content from sections whose headers match any keyword."""
    parts = []
    for header, content in sections:
        if not header:
            continue
        for kw in always_include + keywords:
            if _keyword_matches_header(kw, header):
                parts.append(content)
                break
    return "\n".join(parts)


def _load_filtered_reference_docs(ecosystem: str, is_ui: bool) -> str:
    """Load reference docs filtered to a specific ecosystem."""
    patterns_text = read_file(config.GENERATION_PATTERNS)
    templates_text = read_file(config.PROJECT_TEMPLATES)

    patterns_sections = _split_sections(patterns_text)
    templates_sections = _split_sections(templates_text)

    pattern_kws = _PATTERN_KEYWORDS.get(ecosystem, [])
    template_kws = _TEMPLATE_KEYWORDS.get(ecosystem, [])

    filtered_patterns = _filter_sections(
        patterns_sections, pattern_kws, _ALWAYS_INCLUDE)
    filtered_templates = _filter_sections(
        templates_sections, template_kws, _ALWAYS_INCLUDE_TEMPLATES)

    parts = [
        f"## Generation Patterns\n\n{filtered_patterns}",
        f"## Project Templates\n\n{filtered_templates}",
    ]

    if is_ui:
        ui_styling = read_file(config.UI_STYLING)
        parts.append(f"## UI Styling Guide\n\n{ui_styling}")

    return "\n\n".join(parts)


def _load_reference_docs() -> str:
    """Load all reference docs unfiltered (fallback)."""
    patterns = read_file(config.GENERATION_PATTERNS)
    templates = read_file(config.PROJECT_TEMPLATES)
    ui_styling = read_file(config.UI_STYLING)
    return (
        f"## Generation Patterns\n\n{patterns}\n\n"
        f"## Project Templates\n\n{templates}\n\n"
        f"## UI Styling Guide\n\n{ui_styling}"
    )


# ── Knowledge base loading ───────────────────────────────────────────────────

def _load_knowledge_base(topic: str) -> str:
    """Load any relevant knowledge base entries for this topic."""
    kb_parts = []

    # Load lessons learned
    lessons = read_file(config.LESSONS_LEARNED)
    if lessons.strip() and "Builder will append" not in lessons:
        kb_parts.append(f"## General Lessons Learned\n\n{lessons}")

    # Load any challenge type files
    if config.CHALLENGE_TYPES_DIR.exists():
        for type_file in sorted(config.CHALLENGE_TYPES_DIR.glob("*.md")):
            content = type_file.read_text()
            kb_parts.append(f"## Knowledge Base: {type_file.stem}\n\n{content}")

    return "\n\n".join(kb_parts)


# ── System prompts ───────────────────────────────────────────────────────────

PLANNER_SYSTEM_PROMPT = """You are an expert coding challenge architect. Your job is to plan \
how to organize coding challenges into repos WITHOUT generating any file content.

You will receive a list of challenge descriptions (and optionally instructor notes and \
knowledge base context).

Decide:
1. How to cluster challenges into repos (group by language/framework/theme)
2. What ecosystem each repo uses
3. What creative files the LLM needs to generate for each repo

## Clustering Rules
- Group challenges into ONE repo when they share the same language, framework, build system, and logical theme
- Create SEPARATE repos when challenges have incompatible ecosystems, very different setups, or are standalone modules
- Never mix languages in one repo

## Ecosystem Values
Use exactly one of: "react", "typescript", "vue", "angular", "python", "java", "cpp", "cobol"

## Creative Files
List ONLY the files the LLM needs to generate. Do NOT list config/boilerplate files — those \
are handled automatically. Boilerplate files that are handled for you include: package.json, \
tsconfig.json, vite.config.ts, .gitignore, setupTests.ts, index.html, src/main.tsx, \
src/main.ts, src/index.css, src/App.css, pom.xml, requirements.txt, karma.conf.js, \
angular.json, ChallengeTestListener.java, and ServiceLoader registration.

Creative files you SHOULD list include:
- README.md
- Skeleton source files (e.g., src/Counter.tsx, src/stack.py)
- Test files (e.g., src/Counter.test.tsx, tests/test_stack.py)
- App wrapper (e.g., src/App.tsx for React, src/App.vue for Vue)
- Component CSS files (e.g., src/Counter.css for React)
- For C++: CMakeLists.txt (because it references specific source files)
- For COBOL: tests/run_tests.sh (because it contains challenge-specific test calls)
- For Angular: src/app/app.module.ts, src/app/app.component.ts (because they import specific challenge components)

## Output
Output ONLY a single valid JSON object — no markdown fences, no explanatory text:

{
  "repos": [
    {
      "name": "kebab-case-repo-name",
      "description": "One sentence describing this repo",
      "challenges": ["Challenge 1 name", "Challenge 2 name"],
      "ecosystem": "react",
      "install_command": "npm install",
      "test_command": "npm test",
      "creative_files": ["README.md", "src/Counter.tsx", "src/Counter.test.tsx", "src/Counter.css", "src/App.tsx"],
      "is_ui": true
    }
  ],
  "clustering_rationale": "Brief explanation",
  "challenge_type_notes": "If this is a new/unusual challenge type, describe your approach so it can be saved to the knowledge base. Otherwise empty string."
}"""


REPO_GENERATOR_SYSTEM_PROMPT = """You are an expert coding school challenge designer. Your job is to \
generate the content files for a single challenge repo.

You will receive:
- A repo plan (name, challenges, ecosystem, list of files to generate)
- Reference documentation on how to generate skeleton files and tests (filtered to the relevant ecosystem)
- Optionally: knowledge base entries with templates for specific challenge types
- Optionally: feedback from student agents asking you to revise a previous attempt

IMPORTANT: Config and boilerplate files (package.json, tsconfig.json, vite.config.ts, \
.gitignore, index.html, src/main.tsx, src/main.ts, src/index.css, src/App.css, \
src/setupTests.ts, pom.xml, requirements.txt, karma.conf.js, angular.json, \
ChallengeTestListener.java, ServiceLoader registration) are generated separately — \
do NOT include them in your output. Generate ONLY the creative files listed in the repo plan.

## Challenge Quality Rules
- Skeleton files: give shape without logic. Empty functions, stub methods, placeholder returns
- Test files: tests START FAILING. They turn green as students implement. Never pre-solve anything
- Test progression: existence/smoke → initial state → basic behavior → return values → edge cases
- Stop tests on first failure (--bail 1 for vitest, -x for pytest, etc.)
- Every repo must be fully self-contained and runnable with just install + test commands

## Browser Visualization Rules (UI challenges: React, Vue, Angular)
- ALWAYS generate the App wrapper file that imports and renders EVERY challenge component in its own labeled `<section>`
- React: generate `src/App.tsx` (imports components + App.css)
- Vue: generate `src/App.vue` (imports components, styles in <style> block)
- Angular: generate `src/app/app.module.ts` (declares all components) and `src/app/app.component.ts` (renders all components)

## Debugging Challenge Rules (when applicable)
- Provide intentionally broken code (logic bugs, not syntax errors)
- Tests should pass ONLY when the bugs are fixed
- The README describes only the incorrect behavior — do NOT hint at the cause or the fix
- Do NOT add bug comments or annotations in the code

## Output
Output ONLY a single valid JSON object — no markdown fences, no explanatory text:

{
  "files": {
    "README.md": "full file content...",
    "src/Counter.tsx": "full file content...",
    "src/Counter.test.tsx": "full file content..."
  }
}

All file contents must be complete and valid — no placeholders like "..." inside file content.
Escape all special characters in JSON strings properly.
Ensure the entire response is valid, parseable JSON that starts with { and ends with }."""


REVISE_SYSTEM_PROMPT = """You are fixing specific issues in an existing coding challenge repo.
Do NOT rewrite it from scratch — make targeted, minimal changes to address the feedback.

You will receive:
- The repo description and ecosystem
- The prior creative files (the current state of the repo)
- Feedback from student agents describing exactly what needs to change

Output ONLY the files that need to change. Files not included will be kept exactly as-is.

## Challenge Quality Rules
- Skeleton files: give shape without logic. Empty functions, stub methods, placeholder returns
- Test files: tests START FAILING. They turn green as students implement. Never pre-solve anything
- Test progression: existence/smoke → initial state → basic behavior → return values → edge cases
- Stop tests on first failure (--bail 1 for vitest, -x for pytest, etc.)
- Every repo must be fully self-contained and runnable with just install + test commands

## Debugging Challenge Rules (when applicable)
- Provide intentionally broken code (logic bugs, not syntax errors)
- Tests should pass ONLY when the bugs are fixed
- The README describes only the incorrect behavior — do NOT hint at the cause or the fix
- Do NOT add bug comments or annotations in the code

## Output
Output ONLY a single valid JSON object — no markdown fences, no explanatory text:

{
  "changed_files": {
    "src/Counter.tsx": "full new content for this file...",
    "src/Counter.test.tsx": "full new content for this file..."
  }
}

Include ONLY files that need to be changed or created. Files not listed will be preserved exactly as-is.
All file contents must be complete and valid — no placeholders like "..." inside file content.
Escape all special characters in JSON strings properly.
Ensure the entire response is valid, parseable JSON that starts with { and ends with }."""


# ── Planner ──────────────────────────────────────────────────────────────────

def plan_challenges(
    challenge_descriptions: list[str],
    topic: str = "",
    instructor_notes: str = "",
    existing_repos: list[dict] | None = None,
) -> BuildPlan:
    """
    Lightweight LLM call: decide clustering, ecosystem, file list per repo.

    Args:
        challenge_descriptions: challenges to generate (may include existing ones in amend mode)
        topic: broader topic for knowledge base lookup
        instructor_notes: any guidance from the instructor
        existing_repos: when amending, info about existing repos
                        [{"name": ..., "ecosystem": ..., "challenges": [...]}]
    """
    kb = _load_knowledge_base(topic)

    parts = ["## Challenges to Plan\n"]
    for i, desc in enumerate(challenge_descriptions, 1):
        parts.append(f"{i}. {desc}")

    if instructor_notes:
        parts.append(f"\n## Instructor Notes\n{instructor_notes}")

    if existing_repos:
        parts.append("\n## Existing Repos (amendment context)")
        parts.append("These repos already exist. Preserve their names and structure where "
                      "possible. Add new challenges to existing repos when they fit. Create "
                      "new repos only for challenges that don't fit existing ones.")
        for repo in existing_repos:
            challenges_str = ", ".join(repo.get("challenges", []))
            parts.append(f"- {repo['name']} (ecosystem: {repo['ecosystem']}"
                         f"{', challenges: ' + challenges_str if challenges_str else ''})")

    if kb:
        parts.append(f"\n## Knowledge Base (reuse these patterns)\n{kb}")

    raw = call_llm(
        system=PLANNER_SYSTEM_PROMPT,
        user="\n".join(parts),
        model=config.PLANNER_MODEL,
        max_tokens=config.PLANNER_MAX_TOKENS,
        agent="Builder (Planner)",
    )

    data = parse_json_from_response(raw, context="Builder (Planner)")

    repos = []
    for r in data["repos"]:
        repos.append(RepoSpec(
            name=r["name"],
            description=r["description"],
            challenges=r["challenges"],
            ecosystem=r["ecosystem"],
            install_command=r["install_command"],
            test_command=r["test_command"],
            creative_files=r["creative_files"],
            is_ui=r.get("is_ui", False),
        ))

    return BuildPlan(
        repos=repos,
        clustering_rationale=data.get("clustering_rationale", ""),
        challenge_type_notes=data.get("challenge_type_notes", ""),
    )


# ── Per-repo generator ──────────────────────────────────────────────────────

def generate_repo(
    spec: RepoSpec,
    topic: str = "",
    instructor_notes: str = "",
    revision_feedback: str = "",
    prior_files: dict[str, str] | None = None,
) -> ChallengeRepo:
    """Generate creative files for a single repo, using filtered reference docs."""
    ref_docs = _load_filtered_reference_docs(spec.ecosystem, spec.is_ui)
    kb = _load_knowledge_base(topic)

    parts = [
        "## Repo Plan\n"
        f"Name: {spec.name}\n"
        f"Description: {spec.description}\n"
        f"Ecosystem: {spec.ecosystem}\n"
        f"Challenges: {', '.join(spec.challenges)}\n"
        f"Files to generate: {', '.join(spec.creative_files)}"
    ]

    if instructor_notes:
        parts.append(f"\n## Instructor Notes\n{instructor_notes}")

    if kb:
        parts.append(f"\n## Knowledge Base (reuse these patterns)\n{kb}")

    parts.append(f"\n## Reference Documentation\n{ref_docs}")

    if revision_feedback:
        parts.append(
            f"\n## Revision Required\nStudent agents reviewed your previous attempt and found issues. "
            f"Please fix them:\n\n{revision_feedback}"
        )

    if prior_files:
        parts.append("\n## Your Previous Output (for revision context)")
        parts.append(format_files_for_prompt(prior_files))

    raw = call_llm(
        system=REPO_GENERATOR_SYSTEM_PROMPT,
        user="\n".join(parts),
        model=config.BUILDER_MODEL,
        max_tokens=config.BUILDER_MAX_TOKENS,
        agent="Builder",
    )

    data = parse_json_from_response(raw, context=f"Builder (repo: {spec.name})")

    # Merge boilerplate config files with LLM-generated creative files
    boilerplate = get_boilerplate(spec.ecosystem)
    all_files = {**boilerplate, **data["files"]}  # LLM files override if collision

    return ChallengeRepo(
        name=spec.name,
        description=spec.description,
        challenges=spec.challenges,
        install_command=spec.install_command,
        test_command=spec.test_command,
        files=all_files,
        ecosystem=spec.ecosystem,
    )


# ── Targeted reviser (refinement iterations only) ────────────────────────────

def _revise_repo(
    spec: RepoSpec,
    topic: str,
    instructor_notes: str,
    revision_feedback: str,
    prior_creative: dict[str, str],
) -> ChallengeRepo:
    """
    Targeted revision pass: send only prior creative files + feedback.

    Skips reference docs entirely (prior files already demonstrate the patterns).
    Outputs only the files that need to change; merges result with prior files.
    """
    parts = [
        "## Repo to Fix\n"
        f"Name: {spec.name}\n"
        f"Description: {spec.description}\n"
        f"Ecosystem: {spec.ecosystem}\n"
        f"Challenges: {', '.join(spec.challenges)}"
    ]

    if instructor_notes:
        parts.append(f"\n## Instructor Notes\n{instructor_notes}")

    parts.append(f"\n## Feedback to Address\n{revision_feedback}")

    parts.append("\n## Current Repo Files (fix these)")
    parts.append(format_files_for_prompt(prior_creative))

    raw = call_llm(
        system=REVISE_SYSTEM_PROMPT,
        user="\n".join(parts),
        model=config.BUILDER_MODEL,
        max_tokens=config.BUILDER_MAX_TOKENS,
        agent="Builder",
    )

    data = parse_json_from_response(raw, context=f"Builder revision (repo: {spec.name})")

    # Support both {"changed_files": ...} and fallback {"files": ...} if model slips
    changed_files = data.get("changed_files", data.get("files", {}))

    # Merge: boilerplate < prior creative < changed files (only changed files override)
    boilerplate = get_boilerplate(spec.ecosystem)
    all_files = {**boilerplate, **prior_creative, **changed_files}

    return ChallengeRepo(
        name=spec.name,
        description=spec.description,
        challenges=spec.challenges,
        install_command=spec.install_command,
        test_command=spec.test_command,
        files=all_files,
        ecosystem=spec.ecosystem,
    )


# ── Ecosystem detection (for revision/amendment without re-planning) ─────────

def _detect_ecosystem(files: dict[str, str]) -> str:
    """Infer ecosystem from existing files."""
    filenames = set(files.keys())
    if any(f.endswith(".vue") for f in filenames):
        return "vue"
    if "angular.json" in filenames:
        return "angular"
    if "pom.xml" in filenames:
        return "java"
    if "CMakeLists.txt" in filenames:
        return "cpp"
    if any(f.endswith(".cbl") for f in filenames):
        return "cobol"
    if "requirements.txt" in filenames:
        return "python"
    if any(f.endswith(".tsx") or f.endswith(".jsx") for f in filenames):
        return "react"
    return "typescript"


def _detect_is_ui(ecosystem: str) -> bool:
    return ecosystem in ("react", "vue", "angular")


def _infer_commands(ecosystem: str) -> tuple[str, str]:
    """Return (install_command, test_command) for an ecosystem."""
    commands = {
        "react":      ("npm install", "npm test"),
        "typescript": ("npm install", "npm test"),
        "vue":        ("npm install", "npm test"),
        "angular":    ("npm install", "npm test"),
        "python":     ("pip install -r requirements.txt", "pytest -x"),
        "java":       ("", "mvn test"),
        "cpp":        ("cmake -S . -B build && cmake --build build",
                       "cd build && ctest --stop-on-failure --output-on-failure"),
        "cobol":      ("", "bash tests/run_tests.sh"),
    }
    return commands.get(ecosystem, ("npm install", "npm test"))


# ── Composite build_challenges (preserves orchestrator interface) ────────────

def build_challenges(
    challenge_descriptions: list[str],
    topic: str = "",
    instructor_notes: str = "",
    revision_feedback: str = "",
    prior_files: dict[str, dict[str, str]] | None = None,
    amend_instructions: str = "",
) -> BuildResult:
    """
    Generate challenge repos from a list of challenge descriptions.

    Routes to the appropriate flow:
    - Normal build: plan → generate per repo → assemble BuildResult
    - Revision: skip planner, detect ecosystem from prior files, regenerate with feedback
    - Amendment: plan with existing repo context → selective regeneration

    The function signature is unchanged for orchestrator compatibility.
    """
    if revision_feedback and prior_files:
        return _build_revision(
            challenge_descriptions, topic, instructor_notes,
            revision_feedback, prior_files,
        )

    if amend_instructions:
        return _build_amendment(
            challenge_descriptions, topic, instructor_notes,
            amend_instructions, prior_files,
        )

    # Normal flow: plan then generate per repo
    plan = plan_challenges(challenge_descriptions, topic, instructor_notes)

    repos = []
    for spec in plan.repos:
        repo = generate_repo(spec, topic, instructor_notes)
        repos.append(repo)

    # Save challenge type notes to knowledge base
    notes = plan.challenge_type_notes.strip()
    if notes and notes not in ("", "N/A", "None"):
        _save_challenge_type_notes(topic or challenge_descriptions[0], notes)

    return BuildResult(repos=repos)


def _build_revision(
    challenge_descriptions: list[str],
    topic: str,
    instructor_notes: str,
    revision_feedback: str,
    prior_files: dict[str, dict[str, str]],
) -> BuildResult:
    """Re-generate repos using targeted feedback (skips planner and reference docs)."""
    repos = []

    for repo_name, files in prior_files.items():
        ecosystem = _detect_ecosystem(files)
        is_ui = _detect_is_ui(ecosystem)
        install_cmd, test_cmd = _infer_commands(ecosystem)

        # Identify creative files (non-boilerplate) from prior output
        boilerplate_paths = set(get_boilerplate(ecosystem).keys())
        creative_files = [p for p in files if p not in boilerplate_paths]

        spec = RepoSpec(
            name=repo_name,
            description=challenge_descriptions[0] if challenge_descriptions else "",
            challenges=challenge_descriptions,
            ecosystem=ecosystem,
            install_command=install_cmd,
            test_command=test_cmd,
            creative_files=creative_files,
            is_ui=is_ui,
        )

        # Only send creative files as prior context (skip boilerplate)
        creative_prior = {p: c for p, c in files.items() if p not in boilerplate_paths}

        # Use _revise_repo: skips reference docs, outputs only changed files
        repo = _revise_repo(
            spec, topic, instructor_notes,
            revision_feedback=revision_feedback,
            prior_creative=creative_prior,
        )
        repos.append(repo)

    return BuildResult(repos=repos)


def _build_amendment(
    challenge_descriptions: list[str],
    topic: str,
    instructor_notes: str,
    amend_instructions: str,
    prior_files: dict[str, dict[str, str]] | None,
) -> BuildResult:
    """Amendment mode: plan the amendment scope, then selectively regenerate."""
    # Build existing repo metadata for the planner
    existing_repos = None
    if prior_files:
        existing_repos = []
        for name, files in prior_files.items():
            eco = _detect_ecosystem(files)
            existing_repos.append({"name": name, "ecosystem": eco, "challenges": []})

    # Include amendment instructions in the notes for the planner
    combined_notes = amend_instructions
    if instructor_notes:
        combined_notes = f"{amend_instructions}\n\n{instructor_notes}"

    plan = plan_challenges(
        challenge_descriptions, topic,
        instructor_notes=combined_notes,
        existing_repos=existing_repos,
    )

    repos = []
    for spec in plan.repos:
        prior = prior_files.get(spec.name) if prior_files else None

        if prior:
            # Existing repo — regenerate with amendment context
            boilerplate_paths = set(get_boilerplate(spec.ecosystem).keys())
            creative_prior = {p: c for p, c in prior.items() if p not in boilerplate_paths}

            amendment_feedback = (
                "## Amendment Mode\n\n"
                "You are amending an existing repo. Apply these changes:\n\n"
                f"{amend_instructions}\n\n"
                "Return ALL creative files with COMPLETE contents — "
                "not just the changed ones. You may add new files if needed."
            )

            repo = generate_repo(
                spec, topic, instructor_notes,
                revision_feedback=amendment_feedback,
                prior_files=creative_prior,
            )
        else:
            # New repo — generate from scratch
            repo = generate_repo(spec, topic, instructor_notes)

        repos.append(repo)

    # Save challenge type notes
    notes = plan.challenge_type_notes.strip()
    if notes and notes not in ("", "N/A", "None"):
        _save_challenge_type_notes(topic or challenge_descriptions[0], notes)

    return BuildResult(repos=repos)


# ── File I/O ─────────────────────────────────────────────────────────────────

def _save_challenge_type_notes(topic: str, notes: str) -> None:
    """Persist new challenge type knowledge to the knowledge base."""
    config.CHALLENGE_TYPES_DIR.mkdir(parents=True, exist_ok=True)
    slug = topic.lower().replace(" ", "_").replace("/", "_")[:40]
    dest = config.CHALLENGE_TYPES_DIR / f"{slug}.md"

    if dest.exists():
        existing = dest.read_text()
        dest.write_text(existing + f"\n\n---\n\n{notes}")
    else:
        dest.write_text(f"# Challenge Type: {topic}\n\n{notes}\n")


def write_repos(build_result: BuildResult, output_dir: Path) -> list[Path]:
    """Write all repos from a BuildResult to disk and git-init them."""
    output_dir.mkdir(parents=True, exist_ok=True)
    repo_paths = []

    for repo in build_result.repos:
        repo_dir = output_dir / repo.name
        write_repo_files(repo_dir, repo.files)
        git_init(repo_dir)
        repo_paths.append(repo_dir)

    return repo_paths
